name: mypythonapp
channels:
  - conda-forge
dependencies:
  # -- Runtime dependencies
  # base: list all base dependencies here
  - python>=3.13  # please specify the minimum version of python here
  - versioningit
  # -- Development dependencies
  # utils:
  - pre-commit
  # package building:
  - libmamba
  - libarchive
  - anaconda-client
  - boa
  - python-build
  #- twine  # for uploading to pypi and testpypi
  # test: list all test dependencies here
  - pytest
  # --------------------------------------------------
  # add additional sections such as Qt, etc. if needed
  # --------------------------------------------------
  # if packages are not available on conda, list them here
  #- pip
  #- pip:
  #  - bm3d-streak-removal # example
  #  - pytest-playwright
